"""add owner_user_hidden to paste

Revision ID: 22e25c924240
Revises: 41804fbf1862
Create Date: 2014-12-18 04:08:21.248030

"""

# revision identifiers, used by Alembic.
revision = '22e25c924240'
down_revision = '41804fbf1862'

from alembic import op
import sqlalchemy as sa


from os.path import join, dirname, abspath, realpath
import sys
sys.path.append(realpath(join(dirname(abspath(__file__)), '..')))
import wootpaste.models

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paste', sa.Column('owner_user_hidden', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paste', 'owner_user_hidden')
    ### end Alembic commands ###
