"""drop email unique constraint from user

Revision ID: 4d7d5b95ddef
Revises: 55c4f85c27d8
Create Date: 2014-12-14 17:48:54.965206

"""

# revision identifiers, used by Alembic.
revision = '4d7d5b95ddef'
down_revision = '55c4f85c27d8'

from alembic import op
import sqlalchemy as sa


from os.path import join, dirname, abspath, realpath
import sys
sys.path.append(realpath(join(dirname(abspath(__file__)), '..')))
import wootpaste.models

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_email_key', 'user', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'user_email_key', 'user', ['email'])
    ### end Alembic commands ###
