"""initial

Revision ID: 55c4f85c27d8
Revises: None
Create Date: 2014-12-12 20:00:33.975925

"""

# revision identifiers, used by Alembic.
revision = '55c4f85c27d8'
down_revision = None

from alembic import op
import sqlalchemy as sa


from os.path import join, dirname, abspath, realpath
import sys
sys.path.append(realpath(join(dirname(abspath(__file__)), '..')))
import wootpaste.models

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=1024), nullable=True),
    sa.Column('password', sa.String(length=2049), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('created_at', wootpaste.models.UTCDateTime(), nullable=True),
    sa.Column('updated_at', wootpaste.models.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_reset',
    sa.Column('token', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', wootpaste.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('paste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=True),
    sa.Column('secret', sa.String(length=256), nullable=True),
    sa.Column('created_at', wootpaste.models.UTCDateTime(), nullable=True),
    sa.Column('updated_at', wootpaste.models.UTCDateTime(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.Column('legacy', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('expire_in', sa.Integer(), nullable=True),
    sa.Column('expire_views', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=128), nullable=True),
    sa.Column('visits', sa.Integer(), nullable=True),
    sa.Column('owner_session', sa.String(length=40), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('paste_visit',
    sa.Column('paste_id', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(length=40), nullable=False),
    sa.Column('created_at', wootpaste.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paste_id'], ['paste.id'], ),
    sa.PrimaryKeyConstraint('paste_id', 'session')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paste_visit')
    op.drop_table('paste')
    op.drop_table('user_reset')
    op.drop_table('user')
    ### end Alembic commands ###
